### ISSUE TITLE
Parsing-feil

### ISSUE THREAD

**Issue by bdahle** [navikt/navno-search-frontend#68]
WCAG 4.1.1

Kode validert med [w3 validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.nav.no%2Fsok)
30 feil:

A charset attribute on a meta element found after the first 1024 bytes.
Element ___ not allowed as child of element ___ in this context. (Suppressing further errors from this subtree.) (8) · Hide all · Show all
Element h2 not allowed as child of element button in this context. (Suppressing further errors from this subtree.)
Element div not allowed as child of element button in this context. (Suppressing further errors from this subtree.) (7)
Attribute readonly is only allowed when the input type is date, datetime-local, email, month, number, password, search, tel, text, time, url, or week. (7)
The element ___ must not appear as a descendant of the ___ element. (14) · Hide all · Show all
The element input must not appear as a descendant of the button element. (7)
The element label must not appear as a descendant of the button element. (7)

**Comment by PerOlavM** [comment]
Har skrevet om til ds-react og fjernet en god del av disse, men det er problemer også i ny komponent Accordion.
Hovedproblemet er at det er begrensninger på hva man kan ha inne i en button.
Accordion bruker button for åpning/lukking, W3C vil ikke ha input eller label inne i en button.
