### ISSUE TITLE
Skrive tester

### ISSUE THREAD

**Issue by anders-nom** [navikt/navno-search-frontend#80]
Skrive unittester for frontendkomponenter med @testing-library/react.

**Comment by terjeofnorway** [comment]
Litt frem og tilbake med denne. Jeg begynte å skrive tester og har det i egen [branch](https://github.com/navikt/navno-search-frontend/tree/enhets-tester), men avventer litt til vi har fått det nye søket på plass før jeg (eller noen andre).
