### ISSUE TITLE
Feil i utheving av søkeord i søkeresultat

### ISSUE THREAD

**Issue by macbruker** [navikt/navno-search-frontend#93]
Oppdaget tilfeldigvis at utheving av søkeord noen ganger er pakket inn i dobbelt `<b>`-tag. 

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/1032194/235089646-69efceab-67a6-4d90-9492-b25ae63ee585.png">

**Comment by ojnybo** [comment]
@macbruker Kan du sjekke om dette fortsatt er et problem?

**Comment by macbruker** [comment]
Markup-feilen er der fortsatt, men det er usikkert om vi trenger å fikse nå.

**Comment by bdahle** [comment]
@bjornhun Fikses denne med det nye søket?

**Comment by anders-nom** [comment]
Skal være fikset
